{% set name = "conflowgen" %}
{% set version = "3.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f8084871a6484ce08d1256bcba4fa4eb4f61b2f79bb90dbbad0fc41e19b396a1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 3

requirements:
  host:
    - python >={{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pandas >=1
    - numpy
    - peewee >=3
    - enum_tools >=0.7
    - matplotlib-base
    - plotly
    - python-kaleido >=1.0.0
    - seaborn
    - openpyxl

test:
  imports:
    - conflowgen
  requires:
    - python >={{ python_min }}
    - pytest
    - pip
    - parameterized
  source_files:
    - conflowgen/tests
  commands:
    - pytest conflowgen
    - pip check

about:
  home: https://github.com/1kastner/conflowgen
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'A generator for synthetic container flows at maritime container terminals with a focus is on yard operations'
  doc_url: https://conflowgen.readthedocs.io/
  dev_url: https://github.com/1kastner/conflowgen

extra:
  recipe-maintainers:
    - 1kastner
